POST http://localhost:3001/api/currency
Content-Type: application/json

{"currencyCode": "UAH", "countryId": 3, "conversionRate": 28}

###
#GET http://localhost:3001

#GET http://localhost:3001/api/currency/

#GET http://localhost:3001/api/currency/0

#POST http://localhost:3001/api/currency/

#PUT http://localhost:3001/api/currency/1/0.78

#DELETE http://localhost:3001/api/currency/2

GET http://localhost:3001/api/currency-countryName

#GET http://localhost:3001/api/country

